name: Build PocketBase

on:
  - push
  - pull_request

defaults:
  run:
    working-directory: server

jobs:
  build-pocketbase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
      - run: go mod download
      - run: go build
