on: [push]

jobs:
  cog-check-job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Conventional commits check
        uses: oknozor/cocogitto-action@v2
        with:
          check-latest-tag-only: true
